vscode:
  extensions:
    - magicstack.magicpython@1.1.1:Q+4h8/d9eu9kME/nNfIDlg==
    - kiteco.kite@0.109.0:5JGG8ShofGbQkrlfxHq5ZQ==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - hookyqr.beautify@1.4.11:n9DJEUFbYD/YHaBXxm+pYw==

    - coenraads.bracket-pair-colorizer@1.0.61:+jQByqALW0iXkhpd2yzYzQ==

    - pkief.material-icon-theme@4.6.0:MERinNbuyLgLWxy7kbUsvA==

tasks:
  - init: pip3 install -r requirements.txt