vscode:
  extensions:
    - magicstack.magicpython@1.1.1:Q+4h8/d9eu9kME/nNfIDlg==
    - kiteco.kite@0.142.0:HYAgyl8NGNwJ6eGqJrq1aw==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
 
tasks:
  - init: pip3 install -r requirements.txt