vscode:
  extensions:
    - esbenp.prettier-vscode@5.7.1:4Zx39KyQMoIz7x94PSmDmQ==
    - kevinglasson.cornflakes-linter@0.5.1:KAaMshgHOKan8eojXQ53OQ==
    - kiteco.kite@0.142.0:HYAgyl8NGNwJ6eGqJrq1aw==
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
    - magicstack.magicpython@1.1.1:Q+4h8/d9eu9kME/nNfIDlg==
    - kevinrose.vsc-python-indent@1.12.0:NOHaOm1IToFrG4fit4+hUw==

tasks:
  - init: pip3 install -r requirements.txt