vscode:
  extensions:
    - magicstack.magicpython@1.1.1:Q+4h8/d9eu9kME/nNfIDlg==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - hookyqr.beautify@1.4.11:n9DJEUFbYD/YHaBXxm+pYw==
    - coenraads.bracket-pair-colorizer@1.0.61:+jQByqALW0iXkhpd2yzYzQ==
    - esbenp.prettier-vscode@5.7.1:4Zx39KyQMoIz7x94PSmDmQ==
    - kevinglasson.cornflakes-linter@0.5.1:KAaMshgHOKan8eojXQ53OQ==

tasks:
  - init: pip3 install -r requirements.txt